---
driver:
  name: vagrant

driver_config:
  customize:
    memory: 2048
provisioner:
  name: chef_solo

platforms:
  #- name: ubuntu-12.04
  #- name: ubuntu-14.04
  #- name: centos-6.4
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[yum]     
      - recipe[apache2]
      - recipe[apache2::mod_proxy]
      - recipe[apache2::mod_proxy_http]
      - recipe[apache2::mod_rewrite]
      - recipe[galaxy-httpproxy-cookbook]
      - recipe[galaxy]
    attributes:
